DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS threads;
DROP TABLE IF EXISTS forums;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(250) UNIQUE NOT NULL,
  password VARCHAR(250) NOT NULL
);

CREATE TABLE forums (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(250) NOT NULL,
  creator VARCHAR(250) NOT NULL,
  FOREIGN KEY (creator) REFERENCES users (username)
);

CREATE TABLE threads (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  forum_id INTEGER NOT NULL,
  title VARCHAR(1000) NOT NULL,
  text VARCHAR(1000) NOT NULL,
  author VARCHAR(250) NOT NULL,
  timestamp DATETIME NOT NULL,
  FOREIGN KEY (forum_id) REFERENCES forums (id),
  FOREIGN KEY (author) REFERENCES users (username)
);

CREATE TABLE posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  thread_id INTEGER NOT NULL,
  text VARCHAR(1000) NOT NULL,
  poster VARCHAR(250) NOT NULL,
  timestamp DATETIME NOT NULL,
  FOREIGN KEY (thread_id) REFERENCES threads (id),
  FOREIGN KEY (poster) REFERENCES users (username)
);
